matrix:
- name: Markdown
  sources:
  - '!venv/**/*.md|**/*.md'
  default_encoding: utf-8
  aspell:
    lang: en
  dictionary:
    personal:
      - MCMC
      - MCMCTutorial
      - overlayed
      - pdf
      - MaCh
      - LLH
      - matplotlib
      - numpy
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
