matrix:
- name: Markdown
  sources:
  - '!venv/**/*.md|**/*.md'
  default_encoding: utf-8
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .github/personal_dictionary.txt  # Reference your personal dictionary fil
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
