name: MaCh3 Benchmark

on:
  push:
    branches:
      - feature_benchmark
      - main

permissions:
  # Required permissions for GitHub Pages deployment and content updates
  deployments: write
  contents: write

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - name: Get MaCh3 Validations
        run: |
          cd /opt/
          # Clone the MaCh3Tutorial repository with the current branch
          git clone --branch "${{ github.head_ref }}" https://github.com/mach3-software/MaCh3Tutorial.git MaCh3Validations
          cd MaCh3Validations
          mkdir build
          cd build
          # Configure the project with benchmark support enabled
          cmake ../ -MaCh3Tutorial_Benchmark_ENABLED=TRUE

      - name: Build MaCh3 Validations
        run: |
          cd /opt/MaCh3Validations/build
          make -j4 install # Build and install the project

      - name: Run benchmark
        run: |
          # Source environment setup scripts
          source /opt/MaCh3Validations/build/bin/setup.MaCh3.sh
          source /opt/MaCh3Validations/build/bin/setup.MaCh3Tutorial.sh
          source /opt/MaCh3Validations/build/bin/setup.NuOscillator.sh
          cd /opt/MaCh3Validations/build/CIValidations
          # Run the benchmark and store the output in a file
          ./Benchmark/MaCh3Benchmark | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'catch2' # Specify that the benchmark tool is Catch2
          github-token: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token for authentication
          output-file-path: output.txt # Path to the benchmark output file
          alert-threshold: 200% # Alert threshold for performance degradation
          gh-pages-branch: gh-pages # Branch to store benchmark results
          gh-repository: mach3-software/MaCh3Tutorial # Repository for benchmark results
          summary-always: true # Always show summary in job logs
          fail-on-alert: false # Do not fail the workflow on alert
