name: Image CD

# The events that trigger the workflow
on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # KS: Prevents cancellation of remaining jobs if one fails
      matrix:
        include:
          - os: Alma9
            file: Doc/DockerFiles/Alma9/Dockerfile
            tag_latest: alma9latest

    name: Image CD ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        if [ "${{ github.event_name }}" == 'tag' ]; then
          docker build . --file ${{ matrix.file }} --tag ghcr.io/${{ github.repository_owner }}/mach3tutorial:${{ matrix.os }}${{ github.ref_name }} --build-arg MACH3_VERSION=main
        else
          docker build . --file ${{ matrix.file }} --tag ghcr.io/${{ github.repository_owner }}/mach3tutorial:${{ matrix.tag_latest }} --build-arg MACH3_VERSION=main
        fi

    - name: Push Docker image
      run: |
        if [ "${{ github.event_name }}" == 'tag' ]; then
          docker push ghcr.io/${{ github.repository_owner }}/mach3tutorial:${{ matrix.os }}${{ github.ref_name }}
        else
          docker push ghcr.io/${{ github.repository_owner }}/mach3tutorial:${{ matrix.tag_latest }}
        fi
