# Performs unit and integration testing

name: Validations Python CI 

# The events that trigger the workflow
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/mach3-software/mach3:alma9v1.3.0

    steps:
    - uses: actions/checkout@v4

    - name: Get MaCh3 Validations
      run: |
        cd /opt/
        git clone --branch "${{ github.head_ref }}" https://github.com/mach3-software/MaCh3Tutorial.git MaCh3Validations

    - name: Install pytest
      working-directory: /opt/MaCh3Validations
      run: |
        mkdir python-test-modules
        pip install -r ./CIValidations/PythonTests/requirements.txt -t python-test-modules/

    - name: Validations
      working-directory: /opt/MaCh3Validations
      run: |
        source /opt/root/v6-26-10/bin/thisroot.sh
        export PYTHONPATH=$PYTHONPATH:$PWD/python-test-modules/
        export MACH3=$PWD
        # Temporary until binned and event by event splines are the same
        grep -rl 'XsecCovFile: \["Inputs/SystematicModel.yaml"' . | xargs sed -i 's|XsecCovFile: \["Inputs/SystematicModel.yaml"|XsecCovFile: ["CIValidations/PythonTests/pySystematicModel.yaml"|g'
        python3 -m pytest --config Inputs/FitterConfig.yaml CIValidations/PythonTests
        
