---
# Lint our code and throw error if something is looking fishy in the changes
name: Super Linter

on:
  pull_request:
    branches: [main]

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ReviewDog with yamlint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          level: error # Ensures issues are treated as errors
